Fix for error introduced in nfsen 1.3.8:
p-alik/nfsen pull request #8
Opened 2018-11-14 18:16 UTC by candlerb

Can't use string ("live") as a HASH ref while "strict refs" in use at libexec/NfProfile.pm line 1238.
https://sourceforge.net/p/nfsen/mailman/message/35850749/

2018-11-14 19:13 UTC, p-alik commented
thanks, @candlerb. I'll test it tomorrow.

2018-11-14 19:14 UTC, p-alik commented
#1 covers it also

2018-11-14 19:51 UTC, candlerb commented
Ah OK, just seen that.

The extra `$socket` argument to `DoRebuild` was introduced by the author between `nfsen-1.3.6p1` and `nfsen-1.3.7`.  Your patch 98bf068e reverts this change.  My patch leaves that change, and instead passes the extra argument in a few other places where required.

(Aside: I note that the version tagged "nfsen-1.3.8" in your git repo is not actually nfsen-1.3.8, but is nfsen-1.3.8 plus your patch)

2018-11-15 08:21 UTC, p-alik requested changes
> The extra `$socket` argument to `DoRebuild` was introduced by the author between `nfsen-1.3.6p1` and `nfsen-1.3.7`. Your patch 98bf068 reverts this change. My patch leaves that change, and instead passes the extra argument in a few other places where required.


Without `git revert 98bf068` your PR wouldn't work because `DoRebuild` doesn't expect `$socket`. 

https://github.com/p-alik/nfsen/blob/6d050247cfd4b17dca5c5ddbad3b7dbb32de32f3/libexec/NfProfile.pm#L1189-L1195

Would you enhance your PR by `git revert 98bf068` please.

2018-11-15 08:28 UTC, p-alik commented
> I note that the version tagged "nfsen-1.3.8" in your git repo is not actually nfsen-1.3.8, but is nfsen-1.3.8 plus your patch

Yes, I tried to provide workable alternative to https://sourceforge.net/projects/nfsen/files/stable/nfsen-1.3.8/

If you haven't any objection
I would replace the [nfsen-1.3.8](https://github.com/p-alik/nfsen/releases/tag/nfsen-1.3.8) tab by origin https://sourceforge.net/projects/nfsen/files/stable/nfsen-1.3.8/ plus https://github.com/p-alik/nfsen/pull/8/commits/5e165fdc16f40f88d5c1f25a4ccd2e4130b9c982 if this PR is merged.

2018-11-15 13:15 UTC, candlerb commented
I have added the revert.  (My original patch to 1.3.8 didn't touch that area of code; that's why it didn't complain when I applied the patch)

Beware: if you decide to slip the tag 'nfsen-1.3.8' then anybody who already has this repo checked out [won't pick up the change](https://git-scm.com/docs/git-tag#_on_re_tagging).  It's safer to leave it as it is.

2018-11-16 11:06 UTC, merged

2018-11-16 11:11 UTC, p-alik commented
Thank you, @candlerb.

> Beware: if you decide to slip the tag 'nfsen-1.3.8' then anybody who already has this repo checked out won't pick up the change. It's safer to leave it as it is.

Regarding your advice the tag nfsen-1.3.8 remains untouched.